version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
      - docker
    groups:
      docker-base-image:
        patterns:
          - "nginx"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
    labels:
      - dependencies
      - github-actions
    groups:
      actions:
        patterns:
          - "*"
